export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';

export const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS';
export const CLEAR_COMPLETE_TODOS = 'CLEAR_COMPLETE_TODOS';

export const CHANGE_FILTER = 'CHANGE_FILTER';
